version: '3.8'

services:
  mercure:
    image: dunglas/mercure:v0.15
    restart: unless-stopped
    environment:
      SERVER_NAME: ':80'
      MERCURE_PUBLISHER_JWT_KEY: 'd+fEYc6c8ZfHgBYuvWXLLYaq0eiuqBK4i8XFEbd4SsI='
      MERCURE_SUBSCRIBER_JWT_KEY: 'd+fEYc6c8ZfHgBYuvWXLLYaq0eiuqBK4i8XFEbd4SsI='
      MERCURE_EXTRA_DIRECTIVES: |
        cors_origins *
        publish_origins *
        anonymous
    ports:
      - "3000:80"
    volumes:
      - mercure_data:/data
      - mercure_config:/config
    networks:
      - backend

  database:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: teania123TOP
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "blog", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: "postgresql://postgres:teania123TOP@database:5432/blog?serverVersion=16&charset=utf8"
      MERCURE_URL: "http://mercure/.well-known/mercure"
      MERCURE_JWT_SECRET: "d+fEYc6c8ZfHgBYuvWXLLYaq0eiuqBK4i8XFEbd4SsI="
    volumes:
      - .:/var/www/html
    ports:
      - "8000:8000"
    depends_on:
      database:
        condition: service_healthy
      mercure:
        condition: service_started
    networks:
      - backend

#  nginx:
#    image: nginx:alpine
#    restart: unless-stopped
#    ports:
#      - "8080:80"
#    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf
#      - ./ssl:/etc/nginx/ssl
#    depends_on:
#      - mercure
#    networks:
#      - backend

volumes:
  postgres_data:
  mercure_data:
  mercure_config:

networks:
  backend:
    driver: bridge
